# The URL the site will be built for
base_url = "https://handcraftedsoftware.co"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "juice"

[extra]
juice_logo_name = "Handcrafted Software"
juice_logo_path = "./plaid.png"
juice_extra_menu = [    
]
juice_exclude_menu = [
    "exclude_from_nav"
]
repository_url = "https://github.com/handcrafted-software/handcrafted-software.github.io"
